[project]
name = "base-tool-ml"
version = "0.1.0"
description = "Toolbox de Machine Learning para projetos do IFMaker Lab baseada em Registry Pattern e Configuracao Declarativa."
authors = [
    { name = "Sergio Augusto Jr", email = "sergioaugusto.bezerra.jr@gmail.com" }
]
dependencies = [
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "pyyaml>=6.0.3",
    "tqdm>=4.67.3",
    "matplotlib>=3.10.9",
    "seaborn>=0.13.2",
    "scikit-learn>=1.8.0",
    "pillow>=10.0.0",
    "numpy>=1.26.0",
    "pandas>=2.0.0",
    "opencv-python>=4.11.0.86",
    "onnx>=1.22.0",
    "onnx2tf>=1.28.8",
    "onnxscript>=0.7.1",
    "tensorflow-cpu>=2.21.0",
    "tf-keras>=2.21.0",
    "onnx-graphsurgeon>=0.6.1",
    "psutil>=7.2.2",
    "ai-edge-litert>=2.2.0",
    "sng4onnx>=2.0.1",
    "onnxsim>=0.7.3",
]
requires-python = ">=3.11"

[tool.hatch.build.targets.wheel]
packages = ["base_tool"]

[project.scripts]
base-train = "base_tool.train:main"
base-generate-blender-dataset = "base_tool.synthetic.generate_blender_dataset:main"
base-generate-video-dataset = "base_tool.synthetic.generate_video_dataset:main"
base-recognize = "base_tool.infer:main"
base-export = "base_tool.export:main"

[project.optional-dependencies]
synthetic = [
    "bpy>=4.2.0",
]

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
